### ISSUE TITLE
Is there a way to use a custom model or an event that allows me to add extra data to the table?

### ISSUE THREAD

**Issue by nelson6e65** [laravel/pennant#100]
For example, I use UUID for my migrations to sync some tables to Firebase but stored ID is empty, obviously.

```php
Schema::create('global_features', function (Blueprint $table) {
    $table->uuid('id')->primary();
    $table->string('name');
    $table->string('scope');
    $table->text('value');
    $table->timestamps();

    $table->unique(['name', 'scope']);
});
```

I need to add the `id` in the model on database `creating` event.

Or should I create a custom Driver? 🤔

**Comment by driesvints** [comment]
Hi there, right now there's no way to overwrite the this in the database driver of pennant. You should indeed ship your own driver if you wish to achieve this. This can possible easily be done by overwriting Pennant's database driver and then only overwriting the methods that you need to adjust.
