### ISSUE TITLE
Recent changes to pennant:purge cause command to be registered multiple times

### ISSUE THREAD

**Issue by Orrison** [laravel/pennant#103]
### Pennant Version

1.7.1

### Laravel Version

10.46.0

### PHP Version

8.2.18

### Database Driver & Version

Postgres 15

### Description

Changes in https://github.com/laravel/pennant/pull/96 seem to have caused pennant:purge to be registered multiple times, causing any instantiation of artisan to throw the following error:

```bash
Symfony\Component\Console\Exception\CommandNotFoundException
The "pennant:purge|pennant:clear" command cannot be found because it is registered under multiple names. Make sure you don't set a different name via constructor or "setName()".
```

### Steps To Reproduce

Update to version `1.7.1` run `php artisan tinker` or `php artisan list`

**Comment by timacdonald** [comment]
Hey there,

This is a bug that has been fixed in the framework. Can you please update to `laravel/framework` version `10.48.4` or higher.

**Comment by Orrison** [comment]
> Hey there,
> 
> This is a bug that has been fixed in the framework. Can you please update to `laravel/framework` version `10.48.4` or higher.

Perfect, thank you so much!

**Comment by makroxyz** [comment]
It happens again 

laravel/framework: 11.0.6
laravel/pennant: 1.8.0

**Comment by timacdonald** [comment]
You will need to update to `laravel/framework` version `11.0.8` or higher.
