### ISSUE TITLE
After adding pennant to my project i get the error on the CLI : The "pennant:purge|pennant:clear" command cannot be found because it is registered under multiple names. 

### ISSUE THREAD

**Issue by koch2024** [laravel/pennant#117]
### Pennant Version

1.10

### Laravel Version

10.44.0

### PHP Version

8.2.17

### Database Driver & Version

MariaDB

### Description

After install and adding a feature-flag there occoure the error `   ERROR  The "pennant:purge|pennant:clear" command cannot be found because it is registered under multiple names.  
`  if I run a command like "artisan list" or "artisan pennant:purge" 

### Steps To Reproduce

If i add `pennantSerciceProvider::class` to the `provider`at app.php the freature flags works, but the error occoure in the cli prompt.
![Bildschirmfoto 2024-08-05 um 11 06 53](https://github.com/user-attachments/assets/4f8cfccd-2894-4d37-af75-9c808a58c323)

If I remove the entry from  the `provider` in  `app.php`, and execute the list command it runs perfect but the  freature flags not workoing.

**Comment by timacdonald** [comment]
Hey there,

This is a bug that has been fixed in the framework. Can you please update to `laravel/framework` version `10.48.4` or higher.
