### ISSUE TITLE
Forget all features for one scope

### ISSUE THREAD

**Issue by cthorne91** [laravel/pennant#120]
Hello!

I'm curious if anybody would find this useful. Also, it's possible this feature is available, but I'm missing it in the documentation.

_My use case:_
I have class based features defined. An external system will notify my application server that feature flags have changed for a given scope. There is no way for that system to tell me the feature/value pairs of each flag, only that flags have changed for that user. My goal is to simply remove the cache for each feature for the given scope and let the `Feature::for($user)->active(FeatureA::class)` in my application code reach out to that external system again. For now I'm considering deleting the cache directly from the database. Something like:

```
DB::table('feature_flags')->where('scope', Feature::serializeScope($user))->delete();
``` 

but I would like to see an API like

```
Feature::for($user)->forgetAll();
```

Happy to attempt a PR if this is something others would find useful.

**Comment by timacdonald** [comment]
@cthorne91, you may already use the `forget` method against a specific scope instead of calling `delete` directly against the `DB`.

```php
Feature::for($user)->forget('feature-name');

// or...

Feature::for($user)->forget(['feature-name-1', 'feature-name-2']);
```

You could also call `Feature::for($user)->forget(Feature::defined())` to forget all registered features.

Could be nice to wrap this up in a dedicated `forgetAll` API. We already have a `load` and `loadAll` method which are a similar pairing.

**Comment by cthorne91** [comment]
@timacdonald Thanks for the quick reply. That was my first thought too. However, it appears that the Feature::defined() method will only return features declared using the define(string, closure) method like in [this example](https://laravel.com/docs/10.x/pennant#defining-features) but will not work for class based features that never get _defined_

I should note, I'm using Laravel 10 and Pennant 1.10.0.

```
//example
class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        Feature::define('new-api', fn (User $user) => match (true) {
            $user->isInternalTeamMember() => true,
            $user->isHighTrafficCustomer() => false,
            default => Lottery::odds(1 / 100),
        });
    }
}
```
