### ISSUE TITLE
Method before() not being called with custom feature name

### ISSUE THREAD

**Issue by dnmarques** [laravel/pennant#129]
### Pennant Version

1.13.0

### Laravel Version

10.48.24

### PHP Version

8.1

### Database Driver & Version

MySQL 5.7.27

### Description

Method before() is not being called when feature class has a customized name.

### Steps To Reproduce

Take this feature class:
```
<?php

namespace App\Features;

class Test
{
    public function before($scope): mixed
    {
        return true;
    }

    public function resolve($scope): mixed
    {
        return false;
    }
}
```

Calling the value of this feature calls the before() method correctly:
```
> \Laravel\Pennant\Feature::for(null)->value(\App\Features\Test::class);
= true
```

But if a custom name is added to the class:
```
<?php

namespace App\Features;

class Test
{
    public $name = 'test';

    public function before($scope): mixed
    {
        return true;
    }

    public function resolve($scope): mixed
    {
        return false;
    }
}
```

The method before() is being ignored:
```
> \Laravel\Pennant\Feature::for(null)->value(\App\Features\Test::class);
= false

> \Laravel\Pennant\Feature::for(null)->value('test');
= false
```

**Comment by timacdonald** [comment]
Going to close this now we have a PR up.
