### ISSUE TITLE
Feature: Retrieve a full list of features grouped by values

### ISSUE THREAD

**Issue by ahmedash95** [laravel/pennant#16]
Hello, 

I wanted to take a moment to express my gratitude for this fantastic package. One of the capabilities that initially caught my attention was the ability to group features by their values. This would enable users and app owners to create a page where they could manage and modify any feature-related setting.

I understand that implementing such a feature could be challenging, given the current and future drivers. However, I am eager to write the first implementation attempt. My proposal is to add a method within the supported drivers that allow for the retrieval of features, their values, and the scope count. This information could then be displayed as a table using a CLI command.

What are your thoughts on this idea?

**Comment by timacdonald** [comment]
We will see how the PR goes and close this one.
