### ISSUE TITLE
Add FeatureRetrieve & FeatureResolve events

### ISSUE THREAD

**Issue by cleptric** [laravel/pennant#41]
We at Sentry would be interested in having events fired before a feature gets retrieved or resolved, so we can properly wrap it into a span or add breadcrumbs.
Is this something you would be open to add? If so, I'm happy to provide a PR.

**Comment by timacdonald** [comment]
Hey @cleptric!

We already have a handful of events available for this. I've outlined the relevant events below in hopes that it might help. If you feel that additional are needed, please feel free to attempt a PR with your needs.

`Laravel\Pennant\FeatureResolved`

This event is fired whenever a feature is resolved against a scope, i.e. the feature definition closure is run of the feature class's `resolve` method is run.

If a feature is checked 10 times within a single request this event may fire 0 - 1 times.

`Laravel\Pennant\UnexpectedNullScopeEncountered`

This event is fired when a feature is being resolved when the feature closure of resolve method does not accept `null` and the scope being checked is `null`.

This event is fired while a feature is being resolved.

`Laravel\Pennant\FeatureRetrieved`

This event is fired whenever a feature is retrieved. If a feature is checked 10 times within a request this event is fired 10 times.

`Laravel\Pennant\UnknownFeatureResolved`

This event is fired when a unknonwn feature is being resolved, i.e. if I try and check a feature that doesn't exist `Feature::active('asdfasdf')`

**Comment by cleptric** [comment]
We are mainly interested in adding events that are fired before feature retrieval. Similar to `RequestSending` and `ResponseReceived` for the HTTP client.
