### ISSUE TITLE
Dynamic feature

### ISSUE THREAD

**Issue by jonerickson** [laravel/pennant#52]
Are there any plans to allow dynamic features that can be set at runtime? For example, when integrating with spark, some features should be enabled while on trial, and when the trial is over, the features should be disabled. Also having the ability to set features based on the subscription that is being used. Thanks.

**Comment by timacdonald** [comment]
@JonErickson you can set features based on the subscription in use by checking the subscription in the feature definition.

You could then manually, at runtime, update or clear the feature value when a subscription changes.
