### ISSUE TITLE
Events for Feature Updates

### ISSUE THREAD

**Issue by tylernathanreed** [laravel/pennant#58]
I want to have my UI instantly react to certain feature flag changes. Normally I'd hook up Laravel Echo, and broadcast an event in response to a feature flag update, but I'm not seeing anything I can hook into for that.

Can we get events for when a feature flag changes, so that applications can listen to those changes?

**Comment by driesvints** [comment]
Yeah I think that's something we can do. Feel free to send in a PR for us to look at 👍

**Comment by tylernathanreed** [comment]
Thanks! I'll take a stab at it.
