### ISSUE TITLE
Pennant dashboard

### ISSUE THREAD

**Issue by cosmastech** [laravel/pennant#60]
Sort of a general question here, is there any plan to create a companion dashboard for Pennant? I was envisioning something in the vein of Horizon maybe? That way we could administer app/user level flags.  Maybe something within Nova?

Just curious if this had been discussed before.

**Comment by nunomaduro** [comment]
We haven't yet had a conversation about it, so currently it's not within our immediate plans. Nevertheless, it's possible that you could come across a community dashboard package, possibly for Nova, which utilizes Pennant's database driver.
