### ISSUE TITLE
using GetMorphClass() instead of $scope::class for scope serialization?

### ISSUE THREAD

**Issue by devront-it** [laravel/pennant#63]
### Pennant Version

1.x

### Laravel Version

10.13.5

### PHP Version

8.1

### Description

I am using custom morph maps for my models to ensure that moving a file or extending a model does not break my relations. I also want to use my morph maps with Pennant (database driver) for the same reasons.

I think it would be enough to just replace ``$scope::class`` with ``(new $scope)->getMorphClass()`` inside ``Feature::serializeScope()``, but maybe there are some deeper dependencies that I overlook.

### Steps To Reproduce

Just extend a model and Feature scoping breaks. Or move the model to a new namespace.

**Comment by timacdonald** [comment]
I've opened a PR to introduce a hook for this.

See https://github.com/laravel/pennant/pull/64

**Comment by devront-it** [comment]
Thanks for the great work! :)
