### ISSUE TITLE
Cache values for a short time

### ISSUE THREAD

**Issue by saeedvaziry** [laravel/pennant#68]
## Problem

My application is getting more than 1000 requests per second when I use Pennant, it runs a query per request which makes my DB load increase.

## Proposal

WDYT if we cache the value for 1 minute by default (can be configured in the config file) to not DDoS the database with many queries.

AFAIK Configcat is also doing similar and caching the values for a minute.

**Comment by timacdonald** [comment]
Hi @saeedvaziry,

To reduce DB load make sure you are are eager loading your features. This will ensure that you only have one database query per request: https://laravel.com/docs/10.x/pennant#eager-loading

If you need caching I'd recommend implementing a "Cache Decorator" driver that simply wraps the existing drivers.

We may look at adding something like this as a first party solution in the future, but we aren't looking at adding this right now.
