### ISSUE TITLE
Calling pennant:purge command via Artisan::call() keeps failing

### ISSUE THREAD

**Issue by stephenjude** [laravel/pennant#76]
### Pennant Version

1.5

### Laravel Version

10.31.0

### PHP Version

8.1.15

### Database Driver & Version

MySQL 8.0.32

### Description

Calling pennant:purge command via Artisan::call() keeps failing when done outside the terminal. 

Like calling it inside a queue job class. 

I believe this is because the console commands are registered to only run when the application is running in console.

```
if ($this->app->runningInConsole()) {
    $this->offerPublishing();

    $this->commands([
        \Laravel\Pennant\Commands\FeatureMakeCommand::class,
        \Laravel\Pennant\Commands\PurgeCommand::class,
    ]);
}
```

Can  we have this check removed so the command can be run from anywhere in the application?

### Steps To Reproduce

Create a job class and call the the `pennant:purge` command inside the `handle()` method like this:

```
public function handle(): void
{
    Artisan::call('pennant:purge');
}
```

Screenshot:
<img width="981" alt="image" src="https://github.com/laravel/pennant/assets/31182887/a8a91f29-e5c4-4fe6-8fd3-6157f1c3d835">

**Comment by crynobone** [comment]
You should be able to just do the following:

```php
use Laravel\Pennant\FeatureManager;

app(FeatureManager::class)->store()->purge();
```

**Comment by stephenjude** [comment]
Thank you @crynobone
