### ISSUE TITLE
Feature classes not automatically registered, Documentation error? 

### ISSUE THREAD

**Issue by jeroendelau** [laravel/pennant#92]
### Pennant Version

1.6.0

### Laravel Version

10.46.0

### PHP Version

8.1.4

### Database Driver & Version

MySql 8.1 Lando

### Description

The documentation for features states. 

>  Unlike closure based feature definitions, there is no need to register a class based feature in a service provider.

But they do not behave exactly the same. If you do not Define the feature, it will not show up if you run

```php
# closure based
 $user->features->all();  // => ["my-feature" => false]


# class based
 $user->features->all();  // => []

```

### Closure Based
```php
class AppServiceProvider extends ServiceProvider
{
    ...
    public function boot(): void
    {
        Feature::define('new-api', fn (User $user) => match (true) {
            default = true
        });
    }
}

## Results in
dump($user->features()->all());
['new-api' => true];
```

### Class Based
```php
namespace App\Features;

class NewAPi
{
    public string $name = "new-api";

    public function resolve(mixed $scope): mixed
    {
        return true;
    }
}

class AppServiceProvider extends ServiceProvider
{
    ...
    public function boot(): void
    {
        
    }
}

## Results in
dump($user->features()->all());
[];
```

### Class Based but defined in Service provider
```php
namespace App\Features;

class NewAPi
{
    public string $name = "new-api";

    public function resolve(mixed $scope): mixed
    {
        return true;
    }
}

class AppServiceProvider extends ServiceProvider
{
    ...
    public function boot(): void
    {
        Feature::define(NewAPi::class);
    }
}

## Results in
dump($user->features()->all());
['new-api' => true];;
```

**Comment by timacdonald** [comment]
Hey, @jeroendelau, this is known and documented behaviour. You will want to use discovery if you do not want to register classes manually.

<img width="714" alt="Screenshot 2024-03-08 at 14 34 37" src="https://github.com/laravel/pennant/assets/24803032/7af728ca-35c4-4a0b-85b6-1cd0e752d3ab">

See: https://laravel.com/docs/10.x/pennant#retrieving-multiple-features

**Comment by jeroendelau** [comment]
So sorry, completely missed that.

**Comment by timacdonald** [comment]
No worries at all :)

**Comment by mrvnklm** [comment]
I did too, maybe its worth mentioning it in the `class-based-features` section as it is a requirement for that feature to work.

**Comment by timacdonald** [comment]
@mrvnklm, you do not need to register class based features; registering them is optional. They register when you use them.
